### PR TITLE
switch to BinaryBuilder

### LINKED ISSUE #40: ZMQ Homebrew libs missing when using Anaconda python.app
Using this workaround for PyPlot on Mac OS X - https://github.com/JuliaLang/julia/issues/4116#issuecomment-23057249

Running the Julia symlink from within python.app Pkg.add("ZMQ") fails to install the IJulia required Homebrew libraries. This causes kernel issues when starting IJulia notebooks. 

Other IJulia required packages (libnettle, libgmp, libhogweed) do install correctly.

Original issue - https://github.com/JuliaLang/IJulia.jl/issues/130

cc @staticfloat

### LINKED ISSUE #45: Use provides(AptGet,...) and provides(Yum,...) in build.jl
To cut down on the number of redundant copies of libraries installed would it be worthwhile adding

``` jl
provides(AptGet,"libzmq3",zmq)
```

to `build.jl`?

### LINKED ISSUE #92: Homebrew is expecting a compiler on 10.7
This came up in @stevengj 's class.

### LINKED ISSUE #133: Error in building ZMQ
When trying to run `IJulia` I get error messages from ZMQ. When subsequently trying to build ZMQ I get the following error message:

```julia> Pkg.build("ZMQ")
INFO: Building Homebrew
Already up-to-date.
INFO: Building ZMQ
=========================================[ ERROR: ZMQ ]=========================================

LoadError: KeyError: key "10.90" not found
while loading /Users/lorenz/.julia/v0.5/ZMQ/deps/build.jl, in expression starting on line 35

================================================================================================

========================================[ BUILD ERRORS ]========================================

WARNING: ZMQ had build errors.

 - packages with build errors remain installed in /Users/lorenz/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("ZMQ")`
 - build a single package by running its `deps/build.jl` script

================================================================================================```

### LINKED ISSUE #137: Building requires sudo
When trying to `Pkg.build("ZMQ")` on a shared linux server the process crashed because it was trying to run `sudo yum install czmq`

```
julia> Pkg.build("ZMQ")
INFO: Building ZMQ
Installing dependency czmq via `sudo yum install czmq`:
=====================================[ ERROR: ZMQ ]=====================================

LoadError: could not spawn `sudo yum install czmq`: no such file or directory (ENOENT)
while loading ~/.julia/v0.5/ZMQ/deps/build.jl, in expression starting on line 35
```

Requiring root access to use this seems like a bad idea.

For anyone else with this issue just comment out the line `provides(Yum, "czmq", zmq, os = :Linux)` in `~/.julia/v0.5/ZMQ/deps/build.jl` which will force it to download and build from source and not try to use yum.

### LINKED ISSUE #151: Build Errors on fresh install of Julia 0.6 (Linux Mint)
Just installed julia 0.6. Running Pkg.add("ZMQ") and getting build errors. Any clue what's going on? Do I need to apt install something first such as libzmq3-dev?

```               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  i686-pc-linux-gnu

julia> Pkg.add("ZMQ")
INFO: Initializing package repository /home/nknauf/.julia/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Installing BinDeps v0.6.0
INFO: Installing Compat v0.26.0
INFO: Installing SHA v0.3.3
INFO: Installing URIParser v0.1.8
INFO: Installing ZMQ v0.4.3
INFO: Building ZMQ
INFO: Attempting to Create directory /home/nknauf/.julia/v0.6/ZMQ/deps/downloads
INFO: Downloading file https://github.com/zeromq/zeromq3-x/releases/download/v3.2.5/zeromq-3.2.5.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   608    0   608    0     0   4290      0 --:--:-- --:--:-- --:--:--  4312
100 2034k  100 2034k    0     0  1310k      0  0:00:01  0:00:01 --:--:-- 11.0M
INFO: Done downloading file https://github.com/zeromq/zeromq3-x/releases/download/v3.2.5/zeromq-3.2.5.tar.gz
INFO: Attempting to Create directory /home/nknauf/.julia/v0.6/ZMQ/deps/src
INFO: Attempting to Create directory /home/nknauf/.julia/v0.6/ZMQ/deps
INFO: Directory /home/nknauf/.julia/v0.6/ZMQ/deps already created
INFO: Attempting to Create directory /home/nknauf/.julia/v0.6/ZMQ/deps/builds/zmq
INFO: Changing Directory to /home/nknauf/.julia/v0.6/ZMQ/deps/builds/zmq
configure: WARNING: You are building an unreleased version of 0MQ and asciidoc or xmlto are not installed.
configure: WARNING: Documentation will not be built and manual pages will not be installed.
INFO: Changing Directory to /home/nknauf/.julia/v0.6/ZMQ/deps/builds/zmq
.libs/libzmq_la-ipc_listener.o: In function `zmq::ipc_listener_t::set_address(char const*)':
/home/nknauf/.julia/v0.6/ZMQ/deps/src/zeromq-3.2.5/src/ipc_listener.cpp:124: warning: the use of `tempnam' is dangerous, better use `mkstemp'
ar: `u' modifier ignored since `D' is the default (see `U')
INFO: Changing Directory to /home/nknauf/.julia/v0.6/ZMQ/deps/builds/zmq
================================================================================================================[ ERROR: ZMQ ]================================================================================================================

LoadError: Provider BinDeps.BuildProcess failed to satisfy dependency zmq
while loading /home/nknauf/.julia/v0.6/ZMQ/deps/build.jl, in expression starting on line 35

==============================================================================================================================================================================================================================================

===============================================================================================================[ BUILD ERRORS ]===============================================================================================================

WARNING: ZMQ had build errors.

 - packages with build errors remain installed in /home/nknauf/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("ZMQ")`
 - build a single package by running its `deps/build.jl` script

==============================================================================================================================================================================================================================================
INFO: Package database updated
```

### LINKED ISSUE #162: Error installing ZMQ
`Pkg.build("ZMQ")`

Gives:

```
INFO: Building ZMQ
INFO: Attempting to create directory /home/ayush99/.julia/v0.6/ZMQ/deps/downloads
INFO: Directory /home/ayush99/.julia/v0.6/ZMQ/deps/downloads already exists
INFO: Downloading file https://github.com/zeromq/zeromq3-x/releases/download/v3.2.5/zeromq-3.2.5.tar.gz
INFO: Done downloading file https://github.com/zeromq/zeromq3-x/releases/download/v3.2.5/zeromq-3.2.5.tar.gz
INFO: Attempting to create directory /home/ayush99/.julia/v0.6/ZMQ/deps/src
INFO: Directory /home/ayush99/.julia/v0.6/ZMQ/deps/src already exists
INFO: Attempting to create directory /home/ayush99/.julia/v0.6/ZMQ/deps
INFO: Directory /home/ayush99/.julia/v0.6/ZMQ/deps already exists
INFO: Path /home/ayush99/.julia/v0.6/ZMQ/deps/src/zeromq-3.2.5 already exists
INFO: Attempting to create directory /home/ayush99/.julia/v0.6/ZMQ/deps/builds/zmq
INFO: Directory /home/ayush99/.julia/v0.6/ZMQ/deps/builds/zmq already exists
INFO: Changing directory to /home/ayush99/.julia/v0.6/ZMQ/deps/builds/zmq
=================================[ ERROR: ZMQ ]=================================

LoadError: could not spawn setenv(`/home/ayush99/.julia/v0.6/ZMQ/deps/src/zeromq-3.2.5/configure --prefix=/home/ayush99/.julia/v0.6/ZMQ/deps/usr`,String["PATH=/home/ayush99/.julia/v0.6/ZMQ/deps/usr/bin:/home/Downloads/julia/bin:/home/ayush99/.rbenv/plugins/ruby-build/bin:/home/ayush99/.rbenv/shims:/home/ayush99/.rbenv/bin:/home/ayush99/anaconda3/bin:/home/ayush99/bin:/home/ayush99/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path", "QT_ACCESSIBILITY=1", "UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/1315", "UPSTART_JOB=unity-settings-daemon", "DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-rxDai8ACts", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_DESKTOP=ubuntu", "XDG_SESSION_TYPE=x11", "USER=ayush99", "XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg", "QT_IM_MODULE=ibus", "LESSCLOSE=/usr/bin/lesspipe %s %s", "SESSIONTYPE=gnome-session", "INSTANCE=Unity", "GDMSESSION=ubuntu", "CLUTTER_IM_MODULE=xim", "XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop", "LESSOPEN=| /usr/bin/lesspipe %s", "SHELL=/bin/bash", "XDG_SEAT=seat0", "XAUTHORITY=/home/ayush99/.Xauthority", "GTK_MODULES=gail:atk-bridge:unity-gtk-module", "GNOME_KEYRING_PID=", "GTK_IM_MODULE=ibus", "QT_QPA_PLATFORMTHEME=appmenu-qt5", "XMODIFIERS=@im=ibus", "TERM=xterm-256color", "HOME=/home/ayush99", "VTE_VERSION=4205", "GTK2_MODULES=overlay-scrollbar", "IM_CONFIG_PHASE=1", "COMPIZ_CONFIG_PROFILE=ubuntu", "UPSTART_INSTANCE=", "XDG_CURRENT_DESKTOP=Unity", "LANG=en_IN", "SHLVL=1", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "LOGNAME=ayush99", "XDG_RUNTIME_DIR=/run/user/1000", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "DESKTOP_SESSION=ubuntu", "GDM_LANG=en_US", "RBENV_SHELL=bash", "_=/home/ayush99/Downloads/julia/bin/julia", "GPG_AGENT_INFO=/home/ayush99/.gnupg/S.gpg-agent:0:1", "PWD=/home/ayush99", "DISPLAY=:0", "UPSTART_EVENTS=started starting", "LANGUAGE=en_IN:en", "XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/ayush99", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0", "CPPFLAGS= -I/home/ayush99/.julia/v0.6/ZMQ/deps/usr/include", "LDFLAGS= -L/home/ayush99/.julia/v0.6/ZMQ/deps/usr/lib -Wl,-rpath -Wl,/home/ayush99/.julia/v0.6/ZMQ/deps/usr/lib", "XDG_VTNR=7", "WINDOWID=58725798", "MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path", "XDG_SESSION_ID=c2", "PKG_CONFIG_PATH=/home/ayush99/.julia/v0.6/ZMQ/deps/usr/lib/pkgconfig", "QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1", "QT4_IM_MODULE=xim", "LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:", "GNOME_KEYRING_CONTROL=", "JOB=gnome-session", "OPENBLAS_MAIN_FREE=1"]): no such file or directory (ENOENT)
while loading /home/ayush99/.julia/v0.6/ZMQ/deps/build.jl, in expression starting on line 36

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: ZMQ had build errors.

 - packages with build errors remain installed in /home/ayush99/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("ZMQ")`
 - build a single package by running its `deps/build.jl` script

================================================================================

```

I've also tried deleting and reinstalling, but it doesn't seem to work.

### LINKED ISSUE #164: Homebrew removed zeromq@3.2 (for Mac installation)
Homebrew has recently removed the zeromq@3.2 from their formulas, which is causing the error on the installation for Mac. FYI.
https://github.com/Homebrew/homebrew-core/pull/23083

### LINKED ISSUE #168: Fail to build ZMQ
Hello,
First, my versioninfo is :
```Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  WORD_SIZE: 64
           Microsoft Windows [�汾汾 6.1.7601]
Memory: 3.8901901245117188 GB (1266.68359375 MB free)
Uptime: 8854.9583926 sec
Load Avg:  0.0  0.0  0.0
Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz:
       speed         user       nice        sys       idle        irq ticks
#1  3192 MHz     329848          0     193394    8332918      12698 ticks
#2  3192 MHz     214080          0     235311    8406238        811 ticks
#3  3192 MHz     222722          0     162958    8469824       1638 ticks
#4  3192 MHz     228681          0     253907    8372792        889 ticks
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
Environment:
  ANDROID_HOME = D:\doc\sdk
  ANT_HOME = D:\uiautomator\Environment\adt-x86_64\apache-ant-1.9.4
  CLASSPATH = .;C:\Program Files (x86)\Java\jdk1.8.0_131\lib\dt.jar;C:\Program
iles (x86)\Java\jdk1.8.0_131\lib\tools.jar
  GRADLE_HOME = D:\Program Files\Android\Android Studio\gradle\gradle-3.5
  HOMEDRIVE = C:
  HOMEPATH = \Users\qiumin.HISENSE
  JAVA_HOME = C:\Program Files (x86)\Java\jdk1.8.0_131
  JRE_HOME = C:\Program Files (x86)\Java\jdk1.7.0_79\jre;
  MAVEN_HOME = D:\Program Files (x86)\apache-maven-3.3.9
  PATHEXT = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  PYTHON_HOME = C:\Python27Package Directory: C:\Users\qiumin.HISENSE\.julia\v0.6
4 required packages:
 - BenchmarkTools                0.2.5
 - Flux                          0.5.1
 - IJulia                        1.7.0
 - ZMQ                           0.5.1
35 additional packages:
 - AbstractTrees                 0.1.0
 - Adapt                         0.2.0
 - BinDeps                       0.8.7
 - BinaryProvider                0.2.5
 - BufferedStreams               0.4.0
 - ColorTypes                    0.6.7
 - Colors                        0.8.2
 - CommonSubexpressions          0.0.1
 - Compat                        0.63.0
 - Conda                         0.7.1
 - DataFlow                      0.3.1
 - DiffResults                   0.0.3
 - DiffRules                     0.0.3
 - FixedPointNumbers             0.4.6
 - ForwardDiff                   0.7.3
 - GZip                          0.3.0
 - JSON                          0.17.1
 - Juno                          0.4.0
 - Lazy                          0.12.0
 - LibExpat                      0.4.1
 - Libz                          0.2.4
 - MacroTools                    0.4.0
 - MbedTLS                       0.5.8
 - Media                         0.3.0
 - NNlib                         0.3.0
 - NaNMath                       0.3.1
 - Nullables                     0.0.4
 - Reexport                      0.1.0
 - Requires                      0.4.3
 - SHA                           0.5.6
 - SpecialFunctions              0.3.8
 - StaticArrays                  0.7.0
 - URIParser                     0.3.1
 - WinRPM                        0.3.1
 - ZipFile                       0.5.0
```
After I add "IJulia", when I run "using IJulia" , returns a LoadError :` ZMQ not properly installed. Please run Pkg.build("ZMQ").`
So I do it, still, it returns a LoadError:` None of the selected providers can install dependency zmq. Use BinDeps.debug(package_name) to see avaliable providers.`
All informations of `Pkg.build("ZMQ")` is here:
```julia> Pkg.build("ZMQ")
INFO: Building WinRPM
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.open
suse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building ZMQ
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download 
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
=================================[ ERROR: ZMQ ]=================================


LoadError: None of the selected providers can install dependency zmq.
Use BinDeps.debug(package_name) to see available providers

while loading C:\Users\qiumin.HISENSE\.julia\v0.6\ZMQ\deps\build.jl, in expression starting on line 36

================================================================================


================================[ BUILD ERRORS ]================================


WARNING: ZMQ had build errors.

 - packages with build errors remain installed in C:\Users\qiumin.HISENSE\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("ZMQ")`
 - build a single package by running its `deps/build.jl` script

================================================================================

```

### PR DESCRIPTION
**Pull request by stevengj**
Using the https://github.com/JuliaInterop/ZMQBuilder repo.

Closes #168, closes #164, closes #162, closes #151, closes #137, closes #133, closes #92, closes #45, closes #40.

### CODE REVIEW

**Comment by stevengj** [comment]
AppVeyor failure on 0.7 should be fixed when a new BinaryProvider is tagged, I think.

**Comment by stevengj** [comment]
This temporarily eliminates FreeBSD support, which was added recently (#171), but that should be fixed in the near future once BinaryBuilder adds that platform.

**Comment by marius311** [comment]
I believe this also eliminated MUSL support. Any chance that could be brought back? 

I had been creating lightweight Alpine-based Docker containers to run Jupyter notebooks on mybinder.org, and this no longer seems to work because of this (since Alpine is MUSL-based and Jupyter needs ZMQ)

**Comment by stevengj** [comment]
The latest BinaryBuilder supports musl as well as BSD etc:

https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/v0.0.3/src/RootFS.jl#L120-L141

So, we just need to update ZMQBuilder to use these and push a new tag.

**Comment by marius311** [comment]
Thanks for the quick reply! Incidentally, it would be great if you could do the same for Blosc (although that's less critical for me)

**Pull request merged**
