### PR TITLE
Add docs to repo

### PR DESCRIPTION
**Pull request by joelfrederico**
This follows the Documenter.jl paradigm for creating docs. Right now, it's bare: only the usage section has been moved from the README.md into the docs. I can continue documenting if this is accepted and there is interest.

### CODE REVIEW

**Comment by joelfrederico** [comment]
Some setup is necessary, see: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/

**Comment by stevengj** [comment]
Thanks, this looks good.  (The ZMQ.jl package was created before docstrings existed in Julia, much less Documenter.jl.)

**Comment by stevengj** [comment]
I set up the public/private keys in the Travis and repo settings; does that make this ready to merge?

**Comment by joelfrederico** [comment]
Almost! You'll also need to create a gh-pages branch for tracking doc history and then point the repo's GitHub.io docs to that branch. And also update the repo's byline with the github.io link.

**Comment by stevengj** [comment]
The docs you linked says that the branch will be created automatically by deploydocs if needed?

**Comment by joelfrederico** [comment]
Awesome! At some point I may document things as I learn the lib.

**Pull request merged**
