### PR TITLE
Update to Julia 1.3, add `Project.toml`, use JLL package

### PR DESCRIPTION
**Pull request by staticfloat**
No real rush on this, just needed to use `ZMQ` in a side project, and thought I would upgrade this package while I was at it.

### CODE REVIEW

**Comment by stevengj** [comment]
Is a manifest file required?

**Comment by vtjnash** [comment]
no, some people are for having them and some are against

**Comment by stevengj** [comment]
I would prefer to omit the manifest if it is not required, in the interest of simplicity.

**Comment by stevengj** [comment]
Rebased to fix merge conflict, and removed Manifest.toml.

**Pull request merged**
